//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Story
    {
        public int storyID { get; set; }
        public string title { get; set; }
        public string story1 { get; set; }
        public Nullable<int> premium { get; set; }
        public string url { get; set; }
    
        public virtual Premium Premium1 { get; set; }
    }
}
